### ISSUE TITLE
Affected roads must go on the map

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe-fba#16]
Use the same strategy as buildings - draw them over the basemap, colour coded according to vulnerability

**Comment by NyakudyaA** [comment]
@ann26 I have added the layer to GeoServer. `kartoza:exposed_roads`

**Comment by ann26** [comment]
hi @NyakudyaA when i tried to open it (http://78.47.62.69/geoserver/wms?service=WMS&request=GetMap&layers=kartoza%3Aexposed_roads), it couldn't find the layer
![Screenshot from 2020-01-17 22-37-40](https://user-images.githubusercontent.com/26101337/72624714-fe63c980-3979-11ea-8e71-9454ee28428a.png)

**Comment by NyakudyaA** [comment]
@ann26 http://78.46.133.148/geoserver/kartoza/wms?service=WMS&version=1.1.0&request=GetMap&layers=kartoza:exposed_roads&bbox=106.622978210449,-6.38223075866699,107.423370361328,-5.92312335968018&width=768&height=440&srs=EPSG:4326&format=application/openlayers
You should be fetching the layers from `staging.fbf.kartoza.com`

**Comment by ann26** [comment]
@NyakudyaA thanks
