### ISSUE TITLE
Legend font should match site

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe-fba#18]
see if you can make this work @NyakudyaA

**Comment by NyakudyaA** [comment]
@ann26 We can add the following to the getlegend request

http://staging.fbf.kartoza.com/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=kartoza:exposed_buildings&LEGEND_OPTIONS=fontName:Ubuntu;fontSize:12;fontAntiAliasing:true

Other options we can customize the legend by adding
fontColor:0x000033;
bgColor:0xFFFFEE;
fontStyle:Bold;
