### ISSUE TITLE
Legends should be placed in bottom corners or somewhere neater 

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe-fba#19]
Ask Carina for input here

![image](https://user-images.githubusercontent.com/178003/72503261-2bf22b00-3833-11ea-8578-c966fb2cb08d.png)

**Comment by ann26** [comment]
hi @carina1000 could you add your input here on where to put the legends?

**Comment by carina1000** [comment]
Hi Anita - as Discussed:
- add headings 
- reduce width of vulnerability legend
- bunch legents together
- ability to expand/contact legend.

**Comment by ann26** [comment]
hi @NyakudyaA could you add heading for the legend?
Also by having the heading for the vulnerability score legend, maybe we can reduce the wording of the legend below to become something like
`Low - hazard level >= 2`

![Screenshot from 2020-01-17 23-48-51](https://user-images.githubusercontent.com/26101337/72630005-058fd500-3984-11ea-97a8-ca40cacb4814.png)

**Comment by NyakudyaA** [comment]
@ann26 How about this:
![exposed-bd](https://user-images.githubusercontent.com/2510900/72668180-b2259180-3a2c-11ea-80d4-8a8a5a3ece86.png)

There was no native way to show the title so that's why I cannot alight the layer label but I think it will suffice for now

**Comment by ann26** [comment]
thanks @NyakudyaA for now I have put them at the bottom 
![Screenshot from 2020-01-20 10-53-17](https://user-images.githubusercontent.com/26101337/72697628-181c3100-3b73-11ea-859b-79268f899d00.png)

**Comment by ann26** [comment]
done in https://github.com/inasafe/inasafe-fba/pull/39
