### ISSUE TITLE
Building and roads charts should be tabbed

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe-fba#21]
![image](https://user-images.githubusercontent.com/178003/72503392-84292d00-3833-11ea-9852-89e7821a05c5.png)

Please use tabs and remove the word affected from tab titles.

Also look in the InasSAFE graphics folder for icosn of roads and buildings and place those to the left of the tab titles

**Comment by ann26** [comment]
hi @carina1000 could you give your opinion here please?

**Comment by carina1000** [comment]
@anita please checkhere. I just used the fontawesome icons
![Screenshot 2020-01-17 at 10 47 15](https://user-images.githubusercontent.com/35214829/72597631-cd9e7880-3916-11ea-9dd2-e85310700f8c.png)
