### ISSUE TITLE
Highlight which tab is active

### ISSUE THREAD

**Issue by NyakudyaA** [inasafe/inasafe-fba#34]
# Problem

Since we now have roads and buildings in different tabs we need to let users know which tab is active

![tabs](https://user-images.githubusercontent.com/2510900/72668457-cd45d080-3a2f-11ea-87f1-4a93a4b05ca4.png)

# Solution

Maybe add a color to show which tab is active or make the tab flash
@ann26 maybe Carina will have a better suggestion

**Comment by ann26** [comment]
@carina1000 could you give your input please?
