### ISSUE TITLE
Clean up production db

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe-fba#51]
Some possible candidates for removal are listed here:

![Screenshot 2020-01-27 at 07 43 33](https://user-images.githubusercontent.com/178003/73157540-3cc75a00-40d9-11ea-90fb-21967375d2b2.png)

![Screenshot 2020-01-27 at 07 44 48](https://user-images.githubusercontent.com/178003/73157539-3cc75a00-40d9-11ea-9f8b-625fecb26ebd.png)

**Comment by NyakudyaA** [comment]
@timlinux production DB hasn't been sanitazed yet, We were waiting to get evrything run smoothly in staging before working on priduction

**Comment by NyakudyaA** [comment]
This has been completed now
