### ISSUE TITLE
Please show reporting points on the map

### ISSUE THREAD

**Issue by timlinux** [inasafe/inasafe-fba#60]
Please fetch as geojson so you can draw the markers nicely as pins in OpenLayers.

**Comment by ann26** [comment]
hi @lucernae could you add the url here please?

**Comment by lucernae** [comment]
the geoserver page is here (you had to log in first):
http://78.47.62.69/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.resource.ResourceConfigurationPage?5&name=reporting_point&wsName=kartoza

**Comment by NyakudyaA** [comment]
> the geoserver page is here (you had to log in first):
> http://78.47.62.69/geoserver/web/wicket/bookmarkable/org.geoserver.web.data.resource.ResourceConfigurationPage?5&name=reporting_point&wsName=kartoza

You do not need to login you can access it as geojson http://78.47.62.69/geoserver/kartoza/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=kartoza%3Areporting_point&maxFeatures=50&outputFormat=application%2Fjson

**Comment by lucernae** [comment]
Thanks @NyakudyaA. In the previous comment, I was not able to generate the geojson url, so I put the link first instead so I can come back later.

**Comment by ann26** [comment]
thanks @lucernae and @NyakudyaA
