### ISSUE TITLE
We need to finish supporting roads

### ISSUE THREAD

**Issue by ann26** [inasafe/inasafe-fba#7]
- backend Admire
- frontend (spreadsheet and charts on web page)
- frontend Ask Carina for input

**Comment by NyakudyaA** [comment]
@ann26 have added the summary stats in staging

**Comment by ann26** [comment]
hi @NyakudyaA where's the staging?

**Comment by NyakudyaA** [comment]
Hi @ann26 please check on rancher. You can see the IP address and all other connection details are the same for the DB

**Comment by ann26** [comment]
@NyakudyaA found it, thanks
